### ISSUE TITLE
Not an issue, but sincere gratitude!

### ISSUE THREAD

**Issue by sous-studio** [0xSauel/jpeg-marker-repair#1]
Thank you so much for this wonderful program! Too often people send files over Whatsapp and it cannot be opened in Photoshop. Resaving in other tools is always time consuming. You program is a miracle!! Thank you!!

**Comment by 0xSauel** [comment]
Glad that my program helps you! And now I finally has enough time to refactor. If problem with marker still relevant for you, keep an eye on this repo. New version will be here soon enough, maybe with src this time :)
